### ISSUE TITLE
Provide Swagger documentation

### ISSUE THREAD

**Issue by YZahringer** [saferpay/sndbx#5]
The documentation of a RESTful API with Swagger allows you to generate a client in different languages (Java, C#, Swift, Javascript, PHP, ...), try the API from Web client or import it into Postman.

Simple web editor of Swagger file: [http://editor.swagger.io/](http://editor.swagger.io/)

This would be very useful.

**Comment by Kyoku57** [comment]
I confirm : it would be very useful !

Have you planned to release a OpenAPI 3 / swagger file to help integration of your JSON API ?

**Comment by Hawkkitten** [comment]
We'll consider some sort of JSON-Shema, though it will be in JSON then.
Everything else is noted in the pull-request!

**Comment by YZahringer** [comment]
Finally available on https://test.saferpay.com/Api/swagger/ 🎉
